name: puby
description: Run pub commands for all sub projects in the current directory recursively
version: 1.7.0
homepage: https://github.com/Rexios80/puby

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  yaml: ^3.1.0
  path: ^1.8.1

dev_dependencies:
  rexios_lints: ^1.0.0

executables:
  puby: puby